import type { WorkflowTourStep } from "./types"

export const WORKFLOW_EDITOR_TOUR = [
  {
    id: "workflow-palette",
    anchor: { type: "editor", id: "palette" },
    title: "Node palette",
    body: "Choose building blocks and add them to the workflow canvas.",
    placement: "left",
    media: {
      src: "tour/workflow-palette.mp4",
      poster: "tour/workflow-palette.jpg",
      width: 690,
      height: 716,
      alt: "Dragging a node from the palette onto the canvas",
    },
  },
  {
    id: "workflow-canvas",
    anchor: { type: "editor", id: "canvas" },
    title: "Workflow canvas",
    body: "Connect nodes by dragging from an output handle to another node. Drag the canvas to pan.",
    placement: "top",
    media: {
      src: "tour/workflow-canvas.mp4",
      poster: "tour/workflow-canvas.jpg",
      width: 790,
      height: 392,
      alt: "Connecting two nodes by dragging from an output handle",
    },
  },
  {
    id: "workflow-selection",
    anchor: { type: "editor", id: "canvas" },
    title: "Select several nodes",
    body: "Hold Shift and drag across the canvas to select several nodes, then move, copy, group or delete them together.",
    placement: "top",
    media: {
      src: "tour/workflow-selection.mp4",
      poster: "tour/workflow-selection.jpg",
      width: 880,
      height: 328,
      alt: "Holding Shift and dragging a box to select two nodes",
    },
  },
  {
    id: "workflow-copy-paste",
    anchor: { type: "editor", id: "canvas" },
    title: "Copy and paste",
    body: "Select nodes and press Ctrl+C, then Ctrl+V to paste them where your cursor is. Ctrl+D duplicates in place; with several nodes selected, the toolbar has Copy and Duplicate too.",
    placement: "top",
    media: {
      src: "tour/workflow-copy-paste.mp4",
      poster: "tour/workflow-copy-paste.jpg",
      width: 658,
      height: 442,
      alt: "Copying a node with Ctrl+C and pasting it under the cursor with Ctrl+V",
    },
  },
  {
    id: "workflow-group",
    anchor: { type: "editor", id: "canvas" },
    title: "Group nodes",
    body: "Select nodes and press Group in the toolbar (Ctrl+G) to frame them together. Select a group and press Ctrl+Shift+G to ungroup.",
    placement: "top",
    media: {
      src: "tour/workflow-group.mp4",
      poster: "tour/workflow-group.jpg",
      width: 880,
      height: 366,
      alt: "Grouping two selected nodes from the toolbar, then ungrouping them with Ctrl+Shift+G",
    },
  },
  {
    id: "workflow-search",
    anchor: { type: "editor", id: "toolbar" },
    title: "Search the workflow",
    body: "Press Ctrl+F to find labels, variables and their references. Enter steps through matches; click the counter to see them all and jump to any one.",
    placement: "bottom",
    media: {
      src: "tour/workflow-search.mp4",
      poster: "tour/workflow-search.jpg",
      width: 958,
      height: 560,
      alt: "Searching for a variable, stepping through matches and opening the full list of matches",
    },
  },
  {
    id: "workflow-zoom-in",
    anchor: { type: "editor", id: "zoomIn" },
    title: "Zoom controls",
    body: "Move closer to inspect dense workflows or step back to review the full flow.",
    placement: "top",
  },
  {
    id: "workflow-auto-layout",
    anchor: { type: "editor", id: "autoLayout" },
    title: "Auto layout",
    body: "Clean up node positions and fit the workflow into a readable layout.",
    placement: "top",
    media: {
      src: "tour/workflow-auto-layout.mp4",
      poster: "tour/workflow-auto-layout.jpg",
      width: 958,
      height: 728,
      alt: "A tangled workflow snapping into a tidy row after Auto layout",
    },
  },
  {
    id: "workflow-config-panel",
    anchor: { type: "editor", id: "configPanel" },
    title: "Config panel",
    body: "Select a node to review its details and adjust its label.",
    placement: "left",
  },
] as const satisfies readonly WorkflowTourStep[]
