export const QUICK_ADD_HORIZONTAL_GAP = 180
export const DEFAULT_NODE_COLLISION_MARGIN = 24
export const EDGE_INSERT_VERTICAL_HALF_HEIGHT = 40
export const BRANCH_TRUE_HANDLE_OFFSET_RATIO = 0.34
export const BRANCH_FALSE_HANDLE_OFFSET_RATIO = 0.72
export const QUICK_ADD_CANDIDATE_OFFSETS = [0, -140, 140, -280, 280, -420, 420] as const
export const QUICK_ADD_FALLBACK_OVERFLOW_OFFSET = 480
export const SUBGRAPH_SHIFT_MARGIN = 80
